# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, unique=True, verbose_name='idc 字母简称')),
                ('idc_name', models.CharField(default='', max_length=100, verbose_name='idc 中文名字')),
                ('address', models.CharField(default='', max_length=255, verbose_name='具体的地址，阿里云')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='机房负责人联系电话')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='机房联系email')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='机房联系人')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=32, verbose_name='业务线的名字')),
                ('module_letter', models.CharField(db_index=True, max_length=10, verbose_name='业务线字母简称')),
                ('op_interface', models.CharField(max_length=150, verbose_name='运维对接人')),
                ('dev_interface', models.CharField(max_length=150, verbose_name='业务对接人')),
                ('pid', models.IntegerField(db_index=True, verbose_name='上级业务线id')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.IntegerField(null=True)),
                ('manufacturers', models.CharField(max_length=50, null=True)),
                ('manufacture_date', models.DateField(null=True)),
                ('server_type', models.CharField(max_length=100, null=True)),
                ('sn', models.CharField(db_index=True, max_length=60, null=True)),
                ('os', models.CharField(max_length=50, null=True)),
                ('hostname', models.CharField(db_index=True, max_length=50, null=True)),
                ('inner_ip', models.CharField(max_length=32, null=True, unique=True)),
                ('mac_address', models.CharField(max_length=50, null=True)),
                ('ip_info', models.CharField(max_length=255, null=True)),
                ('server_cpu', models.CharField(max_length=250, null=True)),
                ('server_disk', models.CharField(max_length=100, null=True)),
                ('server_mem', models.CharField(max_length=100, null=True)),
                ('remark', models.TextField(null=True)),
                ('service_id', models.IntegerField(db_index=True, null=True)),
                ('server_purpose', models.IntegerField(db_index=True, null=True)),
                ('check_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('vm_status', models.IntegerField(db_index=True, null=True)),
                ('uuid', models.CharField(db_index=True, max_length=100, null=True)),
                ('idc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Idc')),
            ],
            options={
                'db_table': 'resources_server',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_mark', models.CharField(max_length=255, verbose_name='状态标签')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='statuses',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Statuses'),
        ),
    ]
