# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='statuses',
            field=models.CharField(db_index=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Statuses',
        ),
    ]
