# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 22:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20170920_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='statuses',
            new_name='status',
        ),
    ]
