# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20170920_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_mark', models.CharField(max_length=255, verbose_name='状态标签')),
            ],
        ),
        migrations.RemoveField(
            model_name='server',
            name='status',
        ),
        migrations.AddField(
            model_name='server',
            name='statuses',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Statuses'),
        ),
    ]
