# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_auto_20170917_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='server_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
