# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-18 13:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
