# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-10 06:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='中文名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话号码')),
                ('weixin', models.CharField(max_length=50, verbose_name='weixin id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='与User模型是一对一关系')),
            ],
        ),
    ]
