# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 06:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20170910_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=32, verbose_name='中文名')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('weixin', models.CharField(max_length=50, verbose_name='weixin')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='与User表一对一关系')),
            ],
        ),
    ]
