# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('address', models.CharField(max_length=64, null=True, verbose_name='地址')),
                ('phone', models.CharField(max_length=20, null=True, verbose_name='联系方式')),
            ],
        ),
    ]
