# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_delete_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idc',
            options={'permissions': (('view_idc', '查看idc'),)},
        ),
    ]
